# Generated by Django 3.2.16 on 2022-10-06 02:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_author'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='authors',
            field=models.ManyToManyField(to='core.Author'),
        ),
    ]
